motion-canvas/motion-canvas

packages/docs/docs/getting-started/references.mdx

Just two typos I noticed while reading the (excellent) getting started guide.

Fix two typos in getting-started/references.mdx

---

packages/docs/docs/getting-started/configuration.mdx

fix(docs): fix typo in configuration.mdx

---

CONTRIBUTING.md

Fix all failed links in file `CONTRIBUTING.md`:
- Repo issue link
- Repo issue template link
- Label accepted link
- Main repo branch link

docs: fix links in contribution guide

---

packages/2d/src/partials/Gradient.ts
packages/core/src/signals/CompoundSignalContext.ts

Values passed to a compound signal are now parsed correctly:
```ts
node.position(300); // results in {x: 300, y: 300}
```
Closes: #208
Closes: #210

fix: fix compound property setter

---

packages/docs/docs/getting-started/hierarchy.mdx
packages/docs/docs/getting-started/references.mdx
packages/docs/docs/getting-started/signals.mdx
packages/docs/src/warnings/FirefoxTextWarning.tsx

Since there currently is some confusion for Firefox users, why the `Text` component is not rendered / visible an Info Panel could help aid with confusion.
I put them everywhere where the `Text` component has been used in the docs, since it made the most sense to me.
Related Issue: #179

[Documentation] Info panel for Firefox Users

---

packages/core/src/utils/index.ts
packages/core/src/utils/useDuration.ts
packages/docs/docs/getting-started/time-events.mdx

This Pull Request adds a new helper / utility function that allows for easier creation and usage of `TimeEvent`s for animations.
Furthermore, the documentation has been extended and now features a subsection ("Controlling animation duration with Time Events") under the `Time Events` chapter.
Closes: #171
---
Let's look at the following example where we want to animate the `scale` of a `circle`:
```tsx
import {makeScene2D} from '@motion-canvas/2d';
import {Circle} from '@motion-canvas/2d/lib/components';
import {createRef, useScene} from '@motion-canvas/core/lib/utils';
const circle = createRef<Circle>();
view.add(
<Circle ref={circle} width={320} height={320} fill={'lightseagreen'} />,
);
useScene().timeEvents.register('event');
const duration …
```

feat: add `useDuration` helper

---

packages/2d/src/components/Line.ts

Lines with bigger widths no longer get clipped when the node is cached.
Closes: #205

fix(2d): fix Line cache

---

packages/2d/src/components/Line.ts
packages/2d/src/components/Node.ts
packages/2d/src/components/__logs__/line-without-points.md
packages/2d/src/curves/getPolylineProfile.ts

Lines with no points no longer crash the editor.
When a line with no points is detected, a warning message is logged to the console.
Closes: #212

fix(2d): handle lines with no points

---

packages/docs/docs/getting-started/quickstart.mdx

- Add Caution Admonition (from Docusaurus) on quickstart page in docs in order to alert developers using WSL2 of its inability to alert Vite to file changes unless updated by WSL2 applications.
- Resolves: #214

docs: add warning for Vite not watching files in WSL2

---

packages/docs/docs/getting-started/tweening.mdx

`Color` was introduced here but there's no mention of how to import it, I had to go hunting. I'd suggest putting the import in the example as a comment at the top as I've done here -- this is a style I've seen in many other tutorials/docs.

 make color import clear

---

package.json

Review request: @aarthificial 
Not sure if it was better to change the README.md or the package.json but I went with package.json for consistency with the other scripts. 
Quoting from the README: 
```md
If you want to develop the UI, first build the template project by running: template:build. Next, start ui:serve. ⬅️ This was ui:dev in the package.json
```

fix(packaging): change ui:dev script to ui:serve based on README

---

packages/2d/src/components/Video.ts

Getter functions (`isPlaying`, `getCurrentTime` and `getDuration`) were added to provide access to these properties, which is needed in some cases.
Before there was a 'hacky' way of accessing them via the
`indexing operator` (`[]`).
```ts
videoRef()['playing']()
```
With these changes, these property values can be retrieved in a cleaner and secure way without interfering with core logic.
```ts
videoRef().isPlaying()
```
---
Resolves: https://github.com/motion-canvas/motion-canvas/issues/239

feat(2d): add video component property getter

---

packages/docs/docs/getting-started/flow.mdx

The `flicker` function in the `Animation Flow` chapter of the docs will produce a typescript error with the project's provided `tsconfig.json`.
```
'flicker', which lacks return-type annotation, implicitly has an 'any' yield type.ts(7055)
``` 
While this doesn't stop the example from working in the player, it can lead to confusion for people who are new to Typescript. I've decided to add `Generator` as the return type hint to keep the example simple (no imports required) while still being more correct than `any`.

docs: fix typescript error in example

---

packages/docs/docs/getting-started/quickstart.mdx

I think it might have used to benn "Project" in the project.ts file, but has been changed, since when I just first initialsed the project, it was different.

update Project to makeProject

---

packages/2d/src/components/Text.ts

Fixes #284. `context.fillText()` is not supposed to support newlines in text, so I'm not sure how it worked on Chrome before. `pre` text wrapping is preserved in the same way as text wrapping is done with the segmenter: one text node is added per line of text.

fix(2d): make Text respect textWrap="pre"

---

packages/core/src/tweening/interpolationFunctions.ts

Closes #243.
I'm not 100% happy on this, but it's tricky to get a warning / error in place without disrupting intended functionality with lerping Maps. I'm open to suggestions here on what might be better.

Warn when tweening undefined values

---

packages/2d/src/components/Node.ts
packages/docs/docs/advanced/spawners.mdx

Fixes #270 by calling the spawner function once during construction, to initialize the parents of the spawner objects. A warning in the docs about making sure to null check the parent of spawners would be prudent as well.

fix(2d): call spawnChildren() in constructor to initialize spawner parents

---

packages/core/src/utils/debug.test.ts
packages/core/src/utils/debug.ts
packages/core/src/utils/index.ts

Adds a new `debug` helper function to easily log debug messages with arbitrary payloads to the UI. See #267 for the rationale.
The function uses the logger's built-in functionality to pretty-print complex types by providing the `object` property in the log payload. Since it takes an additional mouse click to open the object dropdown in the UI, the `message` will be the JSON serialized payload itself. This way, you would still get a useful output at a glance which can often be enough when logging simpler types like `Vector2`.
```typescript
import {debug} from "@motion-canvas/core/lib/utils";
const v = Vector2.one;
debug(v);
// Is equivalent to
useLogger().debug({ message: JSON.serialize(v), object: v });
```
When logging primitive values like `string` and `number`,  providing the `object` …

feat(core): add `debug` helper function

---

packages/docs/typedoc.js

In this Pull Request the `typedoc` plugin has been changed to always re-build generated files when
running in `build` mode.
Before the API References did not get re-build when running `npm run docs:build` or using `npx lerna run build` which caused some confusion.
One can check if `docusaurus` runs in `build` mode using the `NODE_ENV` environment variable, which will be set to `production` if that's the case. If the variable is set, we ignore previously build files and re-build them, including the `api.json`.
---
Closes: #294

feat(docs): always re-build api references in `build` mode

---

packages/ui/src/components/controls/Controls.module.scss
packages/ui/src/components/playback/Playback.module.scss
packages/ui/src/components/playback/PlaybackControls.tsx
packages/ui/src/index.scss

This small CSS fix removes the "glossy" effect of <select> tags in Safari

fix(ui): remove glossy <select> effect in Safari

---

packages/2d/src/components/Rect.ts
packages/2d/src/utils/CanvasUtils.ts

Added `smoothCorners` and `cornerSharpness` to `Rect` according to #281 
**Usage:**
```xml
<Rect
width={100}
height={100}
radius={20}
cornerSharpness={.94}
smoothCorners={true}
/>
```
```xml
view.add([
<Rect 
width={100} 
height={100} 
fill={'lightseagreen'} 
radius={20}
>
<Text
fontFamily={'system-ui'}
y={90}
fontSize={20}
fill={'lightseagreen'}
>
Default Corners
</Text>
</Rect>,
<Rect
width={100}
height={100}
fill={'pink'}
x={500}
radius={20}
smoothCorners={true}
cornerSharpness={0.68}
>
<Text
fontFamily={'system-ui'}
y={90}
fontSize={20}
fill={'pink'}
>
Smooth Corners
</Text>
</Rect>,
]);
```

feat(2d): added smooth corners and corner sharpness to rect

---

CONTRIBUTING.md

Fixes an incorrect branch name in the contribution guide. It erroneously referred to the `main` branch as `master`.

docs: fix incorrect branch name in contribution guide

---

packages/2d/src/components/Node.ts

Allows for proper layout calculation for elements that haven't explicitly been added to the scene's view yet.
For reference: This came up as part of #328 where it would allow us to have multiple cameras render the same "view" without having to add it to the scene hierarchy first.

fix(2d): fix layout calculation for nodes not explicitly added to view

---

packages/core/src/Project.ts

Removing this code fixes the problem, but it's unclear why it was added in the first place. I don't see any issue by removing this.
However, please do let me know if this code is essential for a particular scenario. If that is the case, we'll explore alternative solutions to fix the issue.
Issue(#204)

fix(core): playback speed is reset after saving with faulty code (#204).

---

packages/ui/src/components/playback/PlaybackControls.tsx

Press shift + right arrow in the editor to move to the last frame for easier navigation.
Implements #353

feat(ui): shift + right arrow moves to last frame

---

packages/vite-plugin/src/main.ts

The previous implementation tested the full url, including query parameters against the '/' path. Any query parameter in the URL would cause a 404 instead of loading the editor.
Parsing the request URL with the URL class gives us access to the pathname, which does not include query parameters and can be safely compared.
---
I ran into the issue when testing in VS Code and opening `http://localhost:9000/` in the builtin 'Simple Browser'. It simply resulted in a blank page. After some digging I noticed that it automatically appends the query parameter `/?vscodeBrowserReqId=<random number>`, causing the vite server to respond with 404.

fix(vite-plugin): Ignore query param in devserver

---

packages/docs/docs/updating.mdx

A new page for the update guide has been added to the documentation.
In the sidebar it is located below the `Advanced` section since it doesn't really fit to any of the other topics. (Inspired by NextJS Documentation)
This page might contain migration guides as well as breaking changes once we have some.
---
Closes #288

docs: add update guide

---

packages/2d/src/components/CodeBlock.ts
packages/2d/src/components/Image.ts
packages/2d/src/components/Layout.ts
packages/2d/src/components/Line.ts
packages/2d/src/components/Video.ts
packages/2d/src/components/View2D.ts
packages/2d/src/partials/types.ts

- External interfaces for `size` and `lineHeight` no longer use `null` values. Users can use `DEFAULT` to achieve the same thing.
- `lineHeight` supports inheritance like other CSS properties.
- `gap` is now a compound `Vector2` signal.
- Added `width` and `height` as shorthands for `size.x` and `size.y` respectively.
Closes: #352

feat(2d): unify layout properties

---

packages/2d/src/components/CodeBlock.ts

Just a simple typo fix on the comments.

fix: typo on codeblock remove comments

---

packages/2d/src/components/Node.ts
packages/docs/docs/getting-started/hierarchy.mdx
packages/docs/typedoc.js

This PR adds three methods to the `Node` base class to more easily position a node relative to a specific other node in its parent's hierarchy.
- `moveTo` moves to node to the specified position in the parent's children array
- `moveBelow` moves the node one position below the provided sibling node. Will not move the node if it is already positioned lower than the sibling. This method logs an error if the provided node is not a sibling of the current node.
- `moveAbove` moves the node one position above the provided sibling node. Will not move the node if it is already positioned higher than the sibling. This method logs an error if the provided node is not a sibling of the current node.

feat(2d): add moveBelow, moveAbove and moveTo methods to Node

---

packages/2d/src/curves/CircleSegment.ts
packages/2d/src/curves/getPolylineProfile.ts
packages/core/src/tweening/interpolationFunctions.ts

In specific cases, a dot product of two normalized vectors can return a value outside the [-1, 1] range, causing `Math.acos` to return `NaN`. This PR accounts for that.

fix(2d): handle floating point errors in acos

---

packages/core/src/utils/range.test.ts
packages/core/src/utils/range.ts

Adds an optional third parameter `step` to the `range` function which allows users to define the step size of the generated range.
I added a test for the `range` function that covers all the existing and new functionality. I also updated the examples in the existing doc blocks to also show the descending case. As it wasn't super obvious to me how `range(-4)` would behave, for instance.

feat(core): add step parameter to range function

---

packages/docs/src/components/Api/ApiItem.tsx

This rewrites the handler for auto-generated Docs to render out the entire TOC first before rendering just the filtered TOC, which is needed because of some Quirks on Docusaurus' end.
Closes #319

docs: fix #319: hack a fix for bad TOC 

---

package-lock.json
packages/2d/src/components/Image.ts
packages/core/src/utils/index.ts
packages/core/src/utils/proxyUtils.test.ts
packages/core/src/utils/proxyUtils.ts
packages/vite-plugin/package.json
packages/vite-plugin/src/main.ts
packages/vite-plugin/src/proxy-middleware.ts

This PR touches the following packages:
Adds a new `proxy-middleware.ts` which defines a Middleware which proxies GET-Requests using the `/cors-proxy` Endpoint — this is the "main" part of this PR
Also adds a new virtual module, `virtual:proxysettings` , which returns `{enabled: boolean}`.
This is used by the changes in core. This value is either true or false depending on if the user has disabled to proxy by setting `proxy:false` as an option of the vite plugin.
Adds a new util, `viaProxy`.
Anything that might touch a remote resource can use this helper to proxy the request.
The idea behind `viaProxy` is that it will only rewrite if a resource is rewritable.
* it only rewrites if enabled (checks via `virtual:proxysettings`)
* it restricts itself to `http` and `https` to not break inline …

feat(2d, core, vite-plugin): add cors proxy and integrated into Image component

---

packages/2d/src/components/Icon.ts
packages/2d/src/components/index.ts

This introduces the new `<Icon/>` component, a subclass of `Image`.
Closes #305 
Blocked by #357

feat(2d): add Icon Component (#305)

---

packages/2d/src/components/Node.ts

Adds a `zIndex` signal to `Node` and sorts children by this value before drawing them.

feat(2d): add z-index property to nodes

---

packages/docs/docs/components/code-block.mdx

Just a small typo in the docs
`line()` -> `lines()`

docs: fix typo referencing lines() in codeblock

---

package-lock.json
packages/2d/package.json
packages/2d/src/components/CodeBlock.ts
packages/2d/src/components/index.ts

* CodeBlock is now exported
* new stockTheme option with common theme options like github and nord
* new, more granular theme options
* uses the shiki library
closes #396, closes #322

feat: upgraded code-fns for new theme options and lazy loading

---

packages/ui/src/components/sidebar/Rendering.tsx

This is a completely trivial change.
The main reason is Discord's upload limit of 8 GB for non-boosted servers.
Edit: Sorry about the commit lint fail - I remember from the discord that aarthificial can rename the commits anyways.

feat(ui): Add option for 0.25x scale in sidebar

---

packages/2d/src/components/Layout.ts
packages/2d/src/components/Shape.ts
packages/2d/src/components/Text.ts

Currently, the Text component defaults to LTR text direction and hence when setting the offset to -1,-1, we see a slight shift like for RTL texts like this:
https://user-images.githubusercontent.com/24268/220945677-29007823-f869-401c-a491-3c0fd486252b.mp4
With the new property `textDirection` set to `rtl`, we don't see such a shift and text stays steady just like for LTR:
https://user-images.githubusercontent.com/24268/220946030-8b0b7c6e-cd04-442f-bec4-ebfff4c13c83.mp4
Looking for feedback, happyt to make further adjustments. @aarthificial

fix(2d): textDirection property for RTL/LTR text

---

package-lock.json
packages/core/src/app/Player.ts
packages/core/src/app/Renderer.ts
packages/core/src/flow/scheduling.ts
packages/core/src/scenes/GeneratorScene.ts
packages/core/src/scenes/Scene.ts
packages/core/src/scenes/SceneMetadata.ts
packages/core/src/scenes/index.ts
packages/core/src/scenes/timeEvents/EditableTimeEvents.ts
packages/core/src/scenes/timeEvents/ReadOnlyTimeEvents.ts
packages/core/src/scenes/timeEvents/SerializedTimeEvent.ts
packages/core/src/scenes/timeEvents/TimeEvent.ts
packages/core/src/scenes/timeEvents/TimeEvents.ts
packages/core/src/scenes/timeEvents/index.ts
packages/core/src/threading/Thread.ts
packages/core/src/threading/threads.ts
packages/core/src/tweening/spring.ts
packages/core/src/tweening/tween.ts
packages/core/src/utils/useDuration.ts
packages/ui/src/components/timeline/Label.tsx

Time is now always expressed relative to the beginning of the scene.

refactor(core): use relative time

---

packages/docs/docs/getting-started/flow.mdx

My original PR (#266) added the a `Generator` return type to the `flicker` function in the docs to get rid of a Typescript error.  Turns out that this just added a different error because the runner function of the scene expects a `ThreadGeneratorFactory`. 
This has come up a few times already in the Discord as a source of confusion.

docs: use correct return type for flicker function

---

packages/core/src/types/BBox.test.ts
packages/core/src/types/BBox.ts

Adds a new `intersects` method to `BBox` to check if two bounding boxes are overlapping.

feat(core): add intersects method to BBox

---

packages/core/src/types/Vector.ts

I propose to add methods with suffix `XY` that accepts 2 numbers: x and y`.
WDYT?
PS
Of course this PR is just POC. It requires to add more methods with this suffix

Add `XY` types of methods to Vector2

---

packages/ui/src/Editor.tsx
packages/ui/src/components/footer/Footer.module.scss
packages/ui/src/components/footer/Footer.tsx
packages/ui/src/components/footer/index.ts
packages/ui/src/components/layout/ResizeableLayout.tsx
packages/ui/src/components/timeline/Timeline.module.scss
packages/ui/src/components/timeline/Timeline.tsx
packages/ui/src/components/viewport/Viewport.tsx
packages/ui/src/contexts/shortcuts.tsx
packages/ui/src/hooks/useHover.ts
packages/ui/src/hooks/useShortcut.ts
packages/ui/src/main.tsx

Now if you hover some of the components that have shortcut a small preview of the shortcuts will be displayed on the footer:
- Add footer component  to display the shortcuts here
- useHover hook added
- useShorcut hook added - to fetch the shortcut context
- ShortcutProvider to store all the shortcuts and change the current module that it is hover
- Added example use of the shortcut hook for the Timeline component
- Added shortcuts for Viewport

feat(ui): Add hover shortcuts and global shortcuts

---

packages/docs/docs/getting-started/transitions.mdx
packages/docs/src/components/AnimationPlayer/index.tsx

An optional Link prop has been introduced to AnimationPlayer, to specify a separate source link in cases where the name of the example and scene file are not the same.
An alternative solution would be to ensure consistency by updating the file name "transitions-second" to simply "transitions".

fix(docs): transitions example has invalid source code link (#499)

---

packages/examples/src/components/Switch.tsx

- when `Switch` was `initialState=true`, it would have the `offColor` for frame 0
- when `Switch` was `initialState=false`, the position of the circle would be in the on position since it used `this.initialState` instead of `this.initialState()` or `this.isOn`

fix(docs): initialState fixes for Switch Custom Components example

---

packages/2d/package.json
packages/2d/src/components/Txt.ts
packages/2d/src/components/View2D.ts
packages/2d/src/components/index.ts
packages/core/package.json
packages/core/src/decorators/index.ts
packages/core/src/decorators/lazy.ts
packages/core/src/media/AudioManager.ts
packages/core/vitest.config.ts
packages/core/vitest.setup.ts

This PR makes tree shaking work correctly.
The `CodeBlock` and `Latex` nodes are now correctly excluded when not used in the project.
**Previously**
**Now**

feat(core): tree shaking

---

packages/2d/src/components/Rect.ts

Fix a typo in Rect.ts by changing "controll" to "control."

fix(Rect): correct a typo in Rect.ts

---

packages/core/src/types/Matrix.ts
packages/core/src/types/Matrix2D.ts
packages/core/src/types/Type.ts
packages/core/src/types/Vector.test.ts
packages/core/src/types/Vector.ts

This PR adds a few more convenience methods to the `Vector2` type.
- `equals` allows comparing vectors with an additional error threshold to account for floating point inaccuracies.
- `degrees` returns the angle between the vector and the positive x-axis in degrees. A `radians` getter already existed.
- `squaredMagnitude` returns the squared magnitude of the vector. This one is really just for completeness' sake but you gotta save those frames!
I also added the corresponding static methods for `radians`, `degrees`, and `squaredMagnitude` to work similarly to `magnitude`.

feat(core): extend Vector2 type

---

.eslintrc.json
packages/docs/docs/components/custom-components.mdx
packages/docs/docs/components/spline.mdx
packages/docs/src/components/Fiddle/runtime.ts
packages/docs/static/img/media/spline.svg

This PR adds documentation for the new `Spline` node merged in #514. The section `A gentle introduction to splines` is still a work in progress, but the rest should be ready to be reviewed.

docs: add spline documentation

---

packages/docs/docs/components/spline.mdx

Because someone merged too fast.

docs: use Vector2.degrees in spline example

---

packages/docs/docs/migration/updating.mdx

Fixing a small typo, from 'Toubleshooting' to 'Troubleshooting' in section title

fix(docs): small typo in updating.mdx

---

packages/2d/src/components/Curve.ts
packages/2d/src/components/Line.ts
packages/2d/src/components/Spline.ts

This PR extracts a base class `Curve` that `Line` and `Spline` extend from. The `Curve` class is very similar to the old `Line` component except that it doesn't contain line-specific signals such as `points` and `radius`. 
As a side effect of this, `Spline` now no longer a has a `radius` signal since it no longer extends `Line`. This is a Good Thing since it wasn't used anyway and was only there because of inheritance.

refactor(2d): extract curve base component

---

packages/2d/src/components/Curve.ts
packages/2d/src/curves/CircleSegment.ts
packages/2d/src/curves/CurvePoint.ts
packages/2d/src/curves/LineSegment.ts
packages/2d/src/curves/PolynomialSegment.ts
packages/2d/src/curves/Segment.ts
packages/2d/src/curves/getPointAtDistance.ts

This PR does three things:
1. Add a `normal` property to `CurvePoint` that contains the normal of the point
2. Deprecate the `tangent` property of `CurvePoint` as it actually contains the normal of the point in a lot of cases.
3. Use the `normal` to calculate the actual tangent internally for now, e.g. when drawing arrow heads for lines and curves.
Tangents are kept as-is for now as changing them would be a breaking change. They will be fixed in the next major version.
This also fixes an inconsistent behavior in how arrow heads were drawn for linear and non-linear curves.
| Before | After |
| -------|------|
| <img width="460" alt="CleanShot 2023-03-30 at 08 20 18@2x" src="https://user-images.githubusercontent.com/5139098/228747613-3f7552ae-df2e-4f7b-bf58-a6e57a9f0de6.png"> | <img …

fix(2d): calculate arrow orientations for curves correctly

---

packages/docs/docs/components/spline.mdx
packages/docs/src/components/Dropdown/index.tsx
packages/docs/src/components/Fiddle/index.tsx
packages/docs/src/components/Fiddle/parseFiddle.ts
packages/docs/src/components/Fiddle/styles.module.css

Fiddle editors can now include multiple snippets to choose from:
````md
```tsx editor
// snippet Example A
// first example
}
// snippet Example B
// another example
}
```
````
https://user-images.githubusercontent.com/64662184/228849190-916e5ff4-319a-4b6e-967b-e4ddf1002b96.mp4

feat(docs): add snippet toggle for fiddles

---

packages/2d/src/components/Bezier.ts
packages/2d/src/components/CubicBezier.ts
packages/2d/src/components/QuadBezier.ts
packages/2d/src/components/index.ts
packages/docs/docs/components/bezier.mdx
packages/docs/docs/components/custom-components.mdx
packages/docs/docs/components/spline.mdx

This PR adds two new components: `CubicBezier` and `QuadBezier` for drawing cubic and quadratic Bézier curves, respectively.
These components don't really add any new math or logic since I was able to completely reuse the functionality added by the recent splines PR (#514).

Add Bézier curve components

---

packages/docs/docs/components/code-block.mdx

Mention an alternative way to de-select all text: it can be done by setting a value of `.selection()` signal to its default, e.g. "all selected".

CodeBlock: re-setting the signal to its default

---

packages/2d/src/components/CubicBezier.ts
packages/2d/src/components/QuadBezier.ts
packages/2d/src/curves/PolynomialSegment.ts

I also made the `p0X` signals on `CubicBezier` and `QuadBezier` optional because I forgot this last time 😇

fix(2d): fix curve arrow alignment when animating start signal

---

packages/ui/src/Editor.tsx

Just a small typo in the code. Quickly checked, it didn't looked like this element is being referenced anywhere though 🤔

chore(ui): fix typo in ID of the element

---

packages/core/src/flow/loop.ts

There is an extra brace in loop example function

Typo in loop description

---

package-lock.json
packages/docs/package.json

Running `npm run docs:start` is rendering a banner suggesting the following command to be executed to upgrade the docusaurus family of packages:
```
npm i \
@docusaurus/core@latest \
@docusaurus/preset-classic@latest \
@docusaurus/theme-mermaid@latest \
@docusaurus/theme-search-algolia@latest \
@docusaurus/module-type-aliases@latest
```
~I am not exactly certain why changes related to docusaurs package version appear in `package.json` file - suggests docusaurus should probably be updated differently? 🤔 But I decided to open a PR anyone to at least start a discussion about this.~ Re-ran this same command inside `packages/docs`.

chore(docs): update docusaurus to suggested version

---

packages/2d/src/components/Bezier.ts
packages/2d/src/components/Layout.ts
packages/2d/src/components/Line.ts
packages/2d/src/components/Ray.ts
packages/2d/src/components/Spline.ts
packages/2d/src/components/index.ts
packages/2d/src/utils/CanvasUtils.ts

Adds a `Ray` node that represents an individual line segment:
```ts
import {makeScene2D} from '@motion-canvas/2d';
import {Ray} from '@motion-canvas/2d/lib/components';
import {createRef} from '@motion-canvas/core/lib/utils';
const ray = createRef<Ray>();
view.add(
<Ray
ref={ray}
lineWidth={8}
endArrow
stroke={'lightseagreen'}
fromX={-200}
toX={200}
/>,
);
yield* ray().start(1, 1);
yield* ray().start(0).end(0).start(1, 1);
});
```

feat(2d): add Ray node

---

README.md

It is powered by Vite, published with Lerna. And the Motion Canvas logo is not the Vite logo. Probably just a copy-paste that no one saw because it's alt text.

fix: fix misnamed alt text in README.md

---

packages/docs/src/Icon/Image/index.tsx
packages/docs/src/Icon/Split/index.tsx
packages/docs/src/Icon/Text/index.tsx
packages/docs/src/components/Fiddle/FiddleCodeBlock.tsx
packages/docs/src/components/Fiddle/SharedPlayer.ts
packages/docs/src/components/Fiddle/index.tsx
packages/docs/src/components/Fiddle/styles.module.css

Fiddles now support two additional properties:
- `ratio` - the aspect ratio of the preview
- `mode` - the default layout to use
Fiddles can be toggled between the three following modes:
- `code` - is rendered like a standard CodeBlock
- `editor` - an editor with a preview at the top
- `preview` - only the preview without the code
Users can switch between modes using a toolbar in the top right corner.
Example use:
````md
```tsx editor mode=preview ratio=16/9
// some code here
```
````
Closes: #637

feat(docs): improve Fiddle functionality

---

packages/core/src/flow/index.ts
packages/core/src/flow/loopUntil.ts

**Summary**
This PR closes #362 by implementing a `loopUntil()` function. It works in a way similar to `loop()` but uses a `TimeEvent` rather than `iterations` to control the loop. It is now fully updated to work with Motion Canvas version 3 or above.
**Functionality**
This functionality can be achieved by threads, however these are currently undocumented and the approach of adding a new `flow` function would make the process more intuitive for beginners. I followed the naming conventions, and would have renamed `loop()` to `loopFor()` to follow the names of `waitFor()` and `waitUntil()` however this would introduce breaking changes to projects currently using `loop()`.
**Example usage**
```tsx
const circle = createRef<Circle>();
view.add(
<Circle ref={circle} width={320} height={320} …
```

feat(core): add `loopUntil` function for V3

---

packages/core/src/signals/SignalContext.ts
packages/core/src/signals/types.ts

`SignalGenerator` now has four additional methods for complex chaining:
```ts
yield* circle()
// initiate the generator
.scale(0.5, 2)
// tween to another value
.to(2, 2)
// execute a callback
.do(() => circle().fill('red'))
// wait for one second
.wait(1)
// run the given generator
.run(circle().position.y(100, 2))
// tween back to the initial value
.back(2);
```
Closes #480

feat(core): improve `SignalGenerator` chaining

---

package-lock.json
packages/create/index.js
packages/create/package.json

It's now possible to answer the prompts using command-line arguments:
```shell
npm init @motion-canvas@latest -- --name Hello --path ./hello --language ts
```

feat(create): support command-line arguments

---

packages/core/src/app/Project.ts
packages/core/src/app/bootstrap.ts
packages/core/src/app/index.ts
packages/core/src/plugin/DefaultPlugin.ts
packages/core/src/plugin/Plugin.ts
packages/core/src/plugin/makePlugin.ts
packages/ui/src/main.tsx
packages/vite-plugin/src/main.ts
packages/vite-plugin/src/plugins.ts

Plugins can implement the following new hooks:
- `settings` - Modifies the project settings before initialization.
- `project` - Receives the project instance.
- `player` - Receives the player instance.

feat: add new hooks for plugins

---

packages/docs/docs/getting-started/media.mdx

In the Video example without a reference in section about media in the documentation there is a `ref` in the JSX element, but the variable it binds to does not exist. This pull-request fixes that.

fix(docs) nonexistent reference in media documentation

---

packages/docs/docs/getting-started/flow.mdx

Animation flow minor docs change for code example.

docs: fix the code example to retrieve correct generator value

---

packages/core/src/scenes/Random.ts

`gauss(mean, stdev)` will return a normally distributed random value with a given `mean` and `stdev`.
The implementation was ported to TypeScript from Python's `random.gauss()`: https://docs.python.org/3/library/random.html#random.gauss
It includes a small optimization that caches a second independent random value
since the function always generates a pair.

feat(core): add `gauss` function to `Random`

---

packages/docs/docs/getting-started/flow.mdx
packages/docs/docs/getting-started/references.mdx

Some simple fixes, I found while following the tutorial...

Fix typos in docs code

---

packages/2d/src/components/Node.ts

`restore` can now be called without specifying the duration to restore the state immediately.

feat(2d): immediate restore

---

packages/docs/docs/getting-started/flow.mdx

importing makeRef from '@motion-canvas/core/lib/flow' does not work the javascript project. It has to be imported from @motion-canvas/core

Docs: Fix makeRef import for Looping example code snippet

---

packages/ui/src/components/timeline/Timeline.module.scss

Fixes #738 
Now the range handles are visible whenever range is hovered. 
So even when zooming out a lot it's still possible to change the range.
Let me know if you think a better solution could be done.
https://github.com/motion-canvas/motion-canvas/assets/38408878/24aaff8d-9511-48d3-8857-d1342317fa89

fix(ui): add min-width and z-index on hover to range handle

---

packages/docs/docs/getting-started/quickstart.mdx

Added hint that the playback range selector may be the cause of prematurely ending animations

docs: update quickstart

---

packages/2d/src/components/Latex.ts

Resolve #755 
This adds a simple Latex example to the JSDoc of the Latex component.

feat(docs): add Documentation for LaTeX Node to Latex JSDoc

---

packages/2d/src/components/Grid.ts

This PR adds `start` and `end` signals to the `Grid` node. These signals can be used to animate the grid appearing on screen similar to lines or curves work.
```tsx
const grid = createRef<Grid>();
view.add(
<Grid
ref={grid}
width={'100%'}
height={'100%'}
stroke={'#666'}
start={0.5}
end={0.5}
/>,
);
yield* all(
grid().end(1, 1).wait(1).to(0.5, 1),
grid().start(0, 1).wait(1).to(0.5, 1),
);
});
```
https://github.com/motion-canvas/motion-canvas/assets/5139098/38f15add-dbb1-4c91-9a7c-8e0283251b8f

feat(2d): add start and end signals to Grid node

---

packages/docs/docs/getting-started/positioning.mdx

This is a small change to phrasing in the docs that substitutes the phrase "relatively to"  with "relative to".
The latter is more conventional/idiomatic and is also consistent with similar usage contexts in the rest of the docs.
The purpose of the change is to minimise any ambiguity for the user when interpreting the technical content.

docs: consistency of phrasing for relative positioning of nodes

---

packages/2d/src/decorators/defaultStyle.ts
packages/2d/tsconfig.json
packages/core/tsconfig.json
packages/create/template-2d-ts/tsconfig.json
packages/e2e/tsconfig.json
packages/examples/tsconfig.json
packages/template/tsconfig.json
packages/vite-plugin/tsconfig.json

`baseUrl` is used to declare the base directory for resolving non-relative module paths. Our tooling is not configured to support that feature and so the option is not necessary.
Some IDE consider the presence of this option as a hint to use absolute paths for auto imports. Removing it should fix that issue.

build: remove `baseUrl` option

---

packages/core/src/media/AudioManager.ts
packages/vite-plugin/src/main.ts

An audio file edited externally should now be updated without refreshing the entire editor.

feat(core): hot module replacement for audio

---

packages/2d/src/components/SVG.ts
packages/2d/src/components/index.ts
packages/2d/src/utils/diff.test.ts
packages/2d/src/utils/diff.ts

This will add `SVG` component. This component can render SVG and tween between two SVG.
This is part of [add Latex component pull request](https://github.com/motion-canvas/motion-canvas/pull/539).
SVG tweening algorithm support insertion, deletion and tranformation. This algorithm is based on [ManimCommunity TransformMatchingShapes](https://github.com/ManimCommunity/manim/blob/main/manim/animation/transform_matching_parts.py)
This algorithm also support SVG that contain 2 or more element with same id. When number of element with some id in source and target do not match, all element will be transformed wihout insertion or deletion. 
When number of element with some id in source is greater than number of element with that id then excess element will be transformed into target last element …

feat(2d): add SVG component

---

packages/2d/src/components/CodeBlock.ts

I think it would be useful to add a feature that allows for retrieving the current count of CodeBlock's lines.
e.g. I'm using this for my custom 'CodeEditor' component that has numbering on the left side.
```tsx
private createSideNumbers = (n: number): string => Array.from({ length: n }, (_, i) => i + 1).join('\n');
...
<Txt
...
text={() => this.createSideNumbers(this.codeBlock().lineCount())}/>
...
```
BTW: When getting this value it has some delay. It could be probably improved in some way, but I'm not sure how.

feat(2d): add line counter for CodeBlock

---

packages/docs/docs/components/nodes.mdx

Hi, this sentence in the LaTeX chapter is unclear to me, there's a typo in some form.
Either "of" is missing:
> Because we use a canvas renderer, we're rendering the LaTeX to an image instead **of** using a full graphics backend to render the TeX. 
Or commas are missing, in which case I'd suggest simplifying the sentence to:
> Because we use a canvas renderer, we're rendering the LaTeX to an image using a full graphics backend.
PS: thanks for such an impressive project

fix(docs): typo in LaTex (docs/components/nodes.mdx)

---

packages/vite-plugin/src/main.ts

This fix is for solving issue [#764](https://github.com/motion-canvas/motion-canvas/issues/764) and any others that might be caused if the user's folder names include unusual characters which might be considered invalid by JS.

fix: for handling unusual characters in file names

---

packages/vite-plugin/src/main.ts
packages/vite-plugin/src/openInExplorer.ts

This is a PR regarding the OUTPUT DIRECTORY button located in the player's video settings.
When we run `npm` on WSL (Windows Subsystem for Linux) then Motion Canvas tries to execute:
`xdg-open <absolute-path-to-output-dir>`
In the case of WSL it won't work, so we can do something like this:
`bash -c cd <absolute-path-to-output-dir> && explorer.exe .`

Fix OUTPUT DIRECTORY button on WSL

---

packages/core/src/app/Stage.ts
packages/core/src/scenes/GeneratorScene.ts
packages/core/src/scenes/Scene.ts
packages/core/src/transitions/useTransition.ts

This PR adds a third argument to `useTransition`, which is a boolean or signal indicating whether the previous scene is rendered on top of the current scene during the transition.
Solves #369.

feat(core): allow ordering of scenes during transition

---

packages/core/src/app/Player.ts
packages/ui/src/components/animations/borderHighlight.ts
packages/ui/src/components/animations/index.ts
packages/ui/src/components/timeline/Label.tsx
packages/ui/src/components/timeline/RangeSelector.tsx
packages/ui/src/components/timeline/Timeline.tsx
packages/ui/src/components/viewport/Timestamp.tsx
packages/ui/src/components/viewport/Viewport.tsx

- Trying to seek outside the range triggers an animation to convey to users that the range is preventing them from seeking. This is a common problem for new users who sometimes edit the range by mistake and then can't figure out why their animation is not playing past a certain point (the end of the range)
- The range selector no longer uses `useDrag` in favor of pointer captures.
- Fixed the preview playhead not snapping to time events in some edge cases.
- Fixed the order of the duration timestamp - frames are now on the left.

feat(ui): small improvements

---

packages/2d/src/components/Node.ts

Internally clamp the opacity value between 0 and 1. Also add a doc comment describing the range.
Closes: #830

fix(2d): clamp opacity value between 0 and 1

---

package-lock.json
packages/docs/docs/getting-started/configuration.mdx
packages/vite-plugin/package.json
packages/vite-plugin/src/main.ts

Adopting the stale pull request #576 because it failed CI.
Support glob patterns for project files in the vite-plugin.
Please credit @guifeliper as below if squash-merging.
Closes: #324
Co-Authored-By: Guilherme Reis <guifeliper@gmail.com>

feat(vite-plugin): support glob for project files

---

packages/2d/src/components/Txt.ts

Override the `getCacheBBox` method in `Txt` to calculate the cache bounding box based on the actual contents.
In reference to https://github.com/motion-canvas/motion-canvas/pull/525#issuecomment-1468869328.
Closes: #465

fix(2d): calculate Txt cache bbox from contents

---

packages/2d/src/components/Video.ts
packages/2d/src/components/__logs__/reactive-playback-rate.md

Added a `playbackRate` signal to the Video component that mirrors [`HTMLMediaElement.playbackRate`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playbackRate).
Solves #711.

feat(2d): add playbackRate signal to Video component

---

packages/ui/src/components/sidebar/VideoSettings.tsx

Buttons related to rendering are now contained in the same collapsable as the rendering settings. This is meant to prevent people from mistakenly assuming that the rendering options are expanded when they are not.

refactor(ui): collapse render buttons

---

packages/2d/src/components/Line.ts
packages/2d/src/curves/createCurveProfileLerp.ts
packages/2d/src/curves/getPolylineProfile.ts
packages/docs/src/components/Fiddle/index.tsx
packages/docs/src/components/Fiddle/styles.module.css

Adds support for tweening the points of a `Line`.
Uses the same algorithm as the `Path` node with a few adjustments to work better with rounded corners.
https://github.com/motion-canvas/motion-canvas/assets/64662184/837b240b-a020-4482-88ca-5500794ad4be
<details>
<summary>Code</summary>
```ts
import {makeScene2D, Line} from '@motion-canvas/2d';
import {createRef, waitFor} from '@motion-canvas/core';
const line = createRef<Line>();
view.add(
<Line
ref={line}
points={[
[-200, 100],
[200, 100],
[0, -100],
]}
stroke={'lightseagreen'}
fill={'#242424'}
lineWidth={8}
radius={20}
closed
/>,
);
yield* waitFor(0.5);
yield* line()
.points(
[
[-200, 0],
[0, 150],
[200, 0],
[200, -100],
[-200, -100],
],
2,
)
.wait(0.5)
.back(2);
});
```
</details>

feat(2d): support tweening Line points

---

packages/2d/package.json
packages/2d/src/components/Layout.ts
packages/2d/src/components/Node.ts
packages/2d/src/components/View2D.ts
packages/2d/src/components/__tests__/mockScene2D.ts
packages/2d/src/components/__tests__/query.test.tsx
packages/2d/src/jsx-runtime.ts
packages/2d/src/scenes/Scene2D.ts
packages/2d/src/utils/index.ts
packages/2d/src/utils/is.ts
packages/2d/tsconfig.build.json
packages/2d/tsconfig.json
packages/2d/vitest.config.ts
packages/docs/docs/getting-started/hierarchy.mdx
packages/docs/typedoc.js

Introduces multiple helpers for querying the node hierarchy and dealing with type casting.
Finds all descendants of the node that match the given predicate:
```ts
const texts = node.findAll<Txt>(child => child instanceof Txt);
```
Finds the first descendant that matches.
Uses depth-first traversal, like `querySelector` in DOM.
Finds the last descendant that matches.
Order is the same as in `findFirst` but in reverse.
Finds the first ancestor that matches.
---
A helper function for creating `instanceof` predicates.
It's less verbose than manually writing `instanceof` and, thanks to type guards, TypeScript can infer the type of the resulting array automatically:
```ts
const texts = node.find(is(Txt));
```
---
A set of helpers for easier casting. They remove the need for a `(...)` wrapper …

feat(2d): add querying helpers

---

packages/core/src/app/Player.ts

For disable loop mode, this enhancement will seek to the beginning of timeline. Also, this behavior can now be observed for the case where user may hide the timeline. The feature is in line with latest video/animation editors, and hence is made to fit its intuitive usage. 
Closes https://github.com/motion-canvas/motion-canvas/issues/822

feat(core): seek to beginning of timeline in disable loop mode

---

.eslintrc.json
packages/2d/src/components/Node.ts
packages/2d/src/components/__tests__/children.test.tsx
packages/2d/src/scenes/Scene2D.ts
packages/docs/docs/advanced/spawners.mdx

Deprecates `spawner` in favor of `children`.
Reactivity can still be achieved by passing a function as the `children` property:
```tsx
view.add(
<Node>{() => range(count()).map(() => <Node />)}</Node>,
);
```
The property itself is now smarter and will automatically maintain the integrity of the tree.
For example, the following now works perfectly fine:
```tsx
const parentA = createRef<Node>();
const parentB = createRef<Node>();
const child = createRef<Node>();
view.add(
<>
<Node ref={parentA}>
<Node ref={child} />
</Node>
<Node ref={parentB} />
</>,
);
// Steal child from parentA and move it to parentB
parentB().children(child());
// The child is automatically removed from parentA:
// parentA().children() == []
```

feat: better children and spawners

---

packages/core/src/app/Player.ts
packages/core/src/media/AudioManager.ts
packages/ui/src/components/playback/PlaybackControls.tsx

Adds the ability to control the volume of audio through arrow keys (up and down). This will update the volume by 10% increments.
Solves #320 partially.
There's no visible UI element yet since I think some discussion on how that should look like before implementing would be good. 
However, this will at least give people the option to control the volume if they know the button to press.

feat(core & ui): add audio volume control through arrow keys

---

packages/2d/src/components/Layout.ts
packages/2d/src/components/Node.ts
packages/2d/src/components/Txt.test.tsx
packages/2d/src/components/Txt.ts
packages/2d/src/components/TxtLeaf.ts
packages/2d/src/decorators/signal.ts
packages/2d/src/utils/is.ts
packages/core/src/signals/SignalContext.ts
packages/core/src/tweening/interpolationFunctions.ts

Makes it possible to nest `Txt` nodes within each other:
```tsx
view.add(
<Txt ref={text} fill={'white'} fontSize={32} width={720} textWrap>
Whereas recognition of the inherent dignity and of the{' '}
<Txt.i>equal</Txt.i> and inalienable rights of all
members of the human family is the foundation of{' '}
<Txt.b>freedom</Txt.b>, justice and peace in the
world.
</Txt>,
);
```
Nested `Txt` nodes inherit the style of their parent.
The `text` property remains the same, operating exclusively on strings.
Setting the `text` property will remove any nested `Txt` nodes.
Retrieving the value of `text` will return a joined string from all nested nodes:
```tsx
console.log(text().text());
// Whereas recognition of the inherent dignity 
// and of the equal and inalienable rights of all 
// members of …
```

feat(2d): nested Txt nodes

---

packages/core/src/app/Player.ts
packages/ui/src/components/timeline/AudioTrack.tsx
packages/ui/src/components/timeline/Playhead.tsx
packages/ui/src/components/timeline/RangeSelector.tsx
packages/ui/src/components/timeline/Timeline.module.scss
packages/ui/src/components/timeline/Timeline.tsx
packages/ui/src/hooks/useHover.ts
packages/ui/src/utils/index.ts
packages/ui/src/utils/mouse.ts

Makes it possible to scrub the timeline (pressing LMB while dragging left and right)
The range is no longer editable by default. Like the audio track, it requires `SHIFT` to be held down in order to be edited.
Closes: #286

feat(ui): timeline scrubbing

---

packages/docs/src/components/Homepage/Features.tsx

For some reason this `export makeScene()` bothered me – is that valid JS!? (no I don't think it is),
and in fixing it I realized that also the function name is incorrect... which is probably just an API change from long ago, I'm guessing?

Update Features.tsx to use current API

---

packages/docs/src/Icon/Science/index.tsx
packages/docs/src/components/Api/ApiItem.tsx
packages/docs/src/components/Api/Comment/index.tsx
packages/docs/src/components/Release/Issue.tsx
packages/docs/src/css/custom.css
packages/docs/src/theme/Admonition/index.tsx
packages/docs/typedoc.js
tsdoc.json

API marked with `@experimental` is now displayed as such in the docs.

docs: add experimental features

---

packages/ui/src/components/controls/Controls.module.scss
packages/ui/src/components/controls/Slider.tsx
packages/ui/src/components/controls/index.ts
packages/ui/src/components/playback/Playback.module.scss
packages/ui/src/components/playback/PlaybackControls.tsx

Add a volume slider to adjust audio volume in addition to the existing key controls. The slider appears when hovering the sound icon, as described in #856
I had some trouble getting the default `<input type="range"/>` to look consistent accross different browsers, especially with the vertical orientation, so I build a slider component from scratch.
Closes #320

feat(ui): add volume slider

---

packages/2d/src/lib/components/Icon.ts
packages/2d/src/lib/components/Img.ts
packages/2d/src/lib/components/Latex.ts

This is a bugfix that prevents wrong / confusing Warn-Messages for the Icon Component.
The Icon component does not set the `src` Signal explicitly. It overrides the `src`'s getter by defining a  `getSrc` function. 
Because it doesn't set the Signal, a Warning is emitted by the parent `Img`-Class. 
This PR explicitly sets the `src` to `null` to supress the warning.
The `Icon` component also overrides the `setSrc` to tell the User that it is not supported to explicitly set the src.
In the PR, this Warning Message gets supressed until the component is fully initialized. Otherwise setting the `src` to 'null` in the constructor would also trigger that Warning.
Edit: [Additional context from Discord](https://discord.com/channels/1071029581009657896/1073222950028845138/1191273234235134144) …

fix(2d): supress src-Warnings in Icon- and Latex-Component when correctly using component

---

packages/ui/src/components/timeline/RangeSelector.tsx
packages/ui/src/components/timeline/Timeline.module.scss
packages/ui/src/components/timeline/Timeline.tsx
packages/ui/src/contexts/shortcuts.tsx
packages/ui/src/contexts/timeline.tsx

Add the possibility to edit the range directly by "drawing it in" when `SHIFT` and `CTRL` are pressed. To also enable this feature outside of the current range, an additional `rangeContainer` is added as well.
Additionally, pressing `B`/`N` now moves the start/end of the range to the current playhead position. These shortcuts are also added to the footer.
Closes #875

feat(ui): add direct range selection & playhead shortcuts

---

packages/ui/src/components/controls/Controls.module.scss
packages/ui/src/components/controls/NumberInput.tsx
packages/ui/src/components/controls/NumberInputSelect.tsx
packages/ui/src/components/controls/index.ts
packages/ui/src/components/meta/NumberMetaFieldView.tsx
packages/ui/src/components/meta/RangeMetaFieldView.tsx
packages/ui/src/components/meta/Vector2MetaFieldView.tsx

Add a new `NumberInput` component that supports dragging to edit numbers. When hovering over the input, the cursor is a left-right arrow to indicate the dragging option. For the dragging behavior, the `PointerLock` API is used.
In order to edit the value manually via keyboard input, users can click the component without dragging. Dragging is then disabled and the cursor switches to a regular text cursor, allowing text selection. Up and down arrow keys are also supported through the regular `<input type="number"/>` element.
The new `NumberInput` also supports `min`, `max` and `step` properties for input via the arrow keys and via dragging.
Closes #799
https://github.com/motion-canvas/motion-canvas/assets/47495425/6677bb5c-9b73-4819-aa33-4f499ab4b337

feat(ui): add number input dragging

---

package-lock.json
packages/2d/src/lib/components/Node.ts
packages/2d/src/lib/components/View2D.ts
packages/2d/src/lib/partials/ShaderConfig.ts
packages/2d/src/lib/scenes/Scene2D.ts
packages/core/package.json
packages/core/shaders/common.glsl
packages/core/shaders/fragment.glsl
packages/core/src/app/PlaybackStatus.ts
packages/core/src/app/Player.ts
packages/core/src/app/Presenter.ts
packages/core/src/app/Renderer.ts
packages/core/src/app/SharedWebGLContext.ts
packages/core/src/app/__logs__/include-without-preprocessor.md
packages/core/src/app/index.ts
packages/core/src/scenes/GeneratorScene.ts
packages/core/src/scenes/Scene.ts
packages/core/src/scenes/Shaders.ts
packages/core/src/scenes/index.ts
packages/core/src/threading/threads.ts
packages/ui/src/utils/sourceMaps.ts
packages/vite-plugin/package.json
packages/vite-plugin/src/main.ts
packages/vite-plugin/src/partials/index.ts
packages/vite-plugin/src/partials/webgl.ts

Introduces WebGL shaders.
Shaders can be assigned to any node using the `shaders` property. 
See `PossibleShaderConfig` for all accepted values.
In the simplest case, you can just pass a string containing the fragment shader.
The general concept follows the `globalCompositeOperation` from 2D Canvas API.
The shader gets access to two textures:
- source - contains the contents rendered by the node (including its children)
- destination - contains what's already been drawn onto the screen (can be used to achieve a "backdrop blur" effect, for example)
With that in mind, the simplest shader that does nothing would look as follows:
```glsl
#version 300 es
precision highp float;
#include "@motion-canvas/core/shaders/common.glsl"
void main() {
out_color = texture(core_source_tx, source_uv);
}
``` …

feat: webgl shaders

---

packages/core/src/meta/ObjectMetaField.ts

Fixes a bug where `MetaObjectField` passes custom fields into the constructor after calling `clone`, causing the editor to crash due to missing `.get()` methods on the custom fields.

fix: improper cloning of custom fields

---

packages/2d/src/lib/code/CodeRange.ts
packages/2d/src/lib/components/Code.ts

Adds helpers for easier construction of code ranges based on the displayed code:
- `findAllRanges`
- `findFirstRange`
- `findLastRange`
Example:
```ts
// Select the last occurrence of the word "hello":
code().selection(
code().findLastRange('hello')
);
```

feat(2d): code range helpers

---

packages/core/src/flow/run.ts
packages/core/src/threading/Thread.ts
packages/core/src/threading/__logs__/reused-generator.md
packages/core/src/threading/index.ts
packages/core/src/threading/spawn.ts
packages/core/src/threading/threads.test.ts
packages/core/src/threading/threads.ts
packages/internal/transformers/markdown-literals.js

Makes it possible to run generators concurrently without having to `yield` them:
```ts
spawn(function*() {
yield* rect().opacity(0, 1);
})
```
Or:
```ts
spawn(rect().opacity(0, 1))
```
Together with `ref` it makes it easy to run animations upon adding the node to the tree:
```ts
import {Circle, makeScene2D} from '@motion-canvas/2d';
import {waitFor} from '@motion-canvas/core';
import {spawn} from '@motion-canvas/core/lib/threading/spawn';
view.add(
<Circle
ref={node => spawn(node.scale(1, 1))}
scale={0}
width={320}
height={320}
fill={'lightseagreen'}
/>,
);
yield* waitFor(5);
});
```
However we still need to improve the typing of `ref` to make it truly useful. Right now it's always typed as the base `Node` class.

feat(core): spawn function

---

packages/core/src/flow/__logs__/infinite-loop.md
packages/core/src/flow/every.ts
packages/core/src/flow/loop.ts

The first argument can be skipped to run the loop forever.
These two statements are now equivalent:
```ts
yield loop(Infinity, () => /* animation */);
yield loop(() => /* animation */);
```

feat(core): improve loop function

---

README.md
packages/internal/common/marked.js
packages/internal/transformers/markdown-literals.js
packages/internal/vite/markdown-literals.js
packages/template/src/project.meta
packages/template/src/scenes/example.meta
packages/template/src/scenes/example.tsx
packages/template/vite.config.ts

All packages related to the editor can now be developed in unison using a single command:
```bash
npm run template:dev
```
It will start a vite server that watches the `core`, `2d`, `ui`, and
`vite-plugin` packages with proper HMR

refactor: improve template package

---

packages/2d/src/lib/components/TxtLeaf.ts

This PR attempts to fix #934 by expanding the `BBox` returned by `getCacheBBox` for `TxtLeaf` by half of the element's font size horizontally.

934 slanted fonts fix

---

packages/2d/src/lib/code/CodeSignal.ts

Code signal methods like `append` or `replace` now retain nested signals:
```ts
const text = createSignal('');
yield* code().code.append()`\nconsole.log("${text}");`;
// changes to text are still reflected in the code above
yield* text('Hello World!', 1.2, linear);
```

feat(2d): retain reactivity in code transitions

---

packages/ui/src/components/presentation/PresentationControls.tsx

Continuation of #978. Added PowerPoint shortcuts for next/previous slide in presentation mode. Sorry for the second PR, I made some mess on my `main` branch and had to do this the proper way.

feat(ui): support for PowerPoint shortcuts in presentation mode

---

packages/core/src/app/PlaybackManager.ts
packages/core/src/app/Presenter.ts

Hi,
I discovered a bug in the presentation mode. When entering the presentation mode and playing it until the last slide (so getting into the `finished` state), when closing the presentation and opening it again, it was not possible to start playing the slides, even though the play button is active (clicking on it had no effect).
After going through the code, I discovered that on `abort` the finished state is never reset.
For the fix, I was not sure if a separate method was needed to only update the `finished` flag, or an actual `playback.reset` was needed (which I did in the end).

fix(core): reset playback state on presentation abort

---

packages/2d/src/lib/components/Camera.ts
packages/2d/src/lib/components/index.ts
packages/2d/src/lib/scenes/Scene2D.ts
packages/docs/docs/getting-started/camera.mdx
packages/docs/docs/getting-started/configuration.mdx
packages/docs/docs/getting-started/logging.mdx
packages/docs/docs/getting-started/media.mdx
packages/docs/docs/getting-started/presentation.mdx
packages/docs/docs/getting-started/rendering/index.mdx

This PR adds an orthographic camera node.
There a still a few kinks that I'd like to work out before merging this:
- The `hit` method selects the correct object, but the actual overlay in the editor is offset. I'm not sure why this happens.
- I would like most of the camera's methods to return a `SignalGenerator` in order to be chainable. I'm not sure what the best way to do this would be, however.

feat(2d): add camera node

---

packages/ui/src/main.tsx

**Summary**
This PR adds two URL parameters, `?render` and `?present`. These can be used for quick access to common UI functionality, leading to a somewhat automated process. (quick and dirty hack for #415? not headless, but automated)
**Functionality**
Simply append the URL in your browser with `?render` to automatically start rendering once the page loads, or `?present` to automatically load into presentation mode.
**Example usage**

feat(ui): add `?render` and `?present` url params

---

packages/docs/docs/getting-started/quickstart.mdx

When I tried to render my project without the `?scene` import postfix I got the following errors.
I'd like to propose to add a hint about the import postfix to the quickstart guide. 
```ts import {makeProject} from '@motion-canvas/core';
import podcast from "./scenes/podcast/podcast"; // without ?scene
export default makeProject({
scenes: [ podcast],
});
```

docs: add hint about `?scene` import path to quickstart guide

---

packages/ui/src/components/footer/Footer.module.scss
packages/ui/src/components/footer/Footer.tsx
packages/ui/src/contexts/shortcuts.tsx

Shortcuts can now trigger modal actions:
1. The shortcut handler can return an action object to start it.
2. The action receives the following pointer events, blocking other shortcuts from being used.
3. Pressing the left or right mouse button completes or cancels the action respectively.

feat(ui): add modal actions

---

packages/docs/docs/components/path.mdx

(Documentation) The "Path" page tried to link to "Spline", but it used invalid syntax `[display][link]` instead of `[display](link)`, resulting in a result that's broken visually and, more importantly, doesn't actually link. This simple commit fixes that.

docs: proper link syntax to Spline from Path

---

packages/core/src/app/PlaybackManager.ts
packages/core/src/scenes/GeneratorScene.ts
packages/core/src/scenes/Scene.ts

This PR updates seeking-related logic in `PlaybackManager` to ensure both scenes are visible when seek position is in the middle of transition. Previously, it could occur that only the `currentScene` will be rendered, especially visible when seeking backwards.
Before:
https://github.com/user-attachments/assets/e83742a1-d3e5-4e3a-a848-f7d0e1b16d5b
After:
https://github.com/user-attachments/assets/9c834528-a812-46d2-891e-305d38f0ad56

fix(core): always show both scenes when seeking mid-transition

---

packages/core/src/media/AudioManager.ts

Fixes #1155 
When preparing to play, the player checks whether the audio should be playing by following this logic:
https://github.com/motion-canvas/motion-canvas/blob/13c9de85280cc1b893a178b9d6eecd8d639fd7bb/packages/core/src/app/Player.ts#L412-L413
One of the things it checks is whether the current time is in the audio's range.
When we look at `AudioManager.isInRange`'s implementation:
https://github.com/motion-canvas/motion-canvas/blob/main/packages/core/src/media/AudioManager.ts#L60-L62
we notice that it doesn't account for the audio offset, which causes the issue.

Fix audio not playing when playhead is after audio's duration (not accounting for offset)

---

packages/2d/src/lib/components/TxtLeaf.ts

Correctly calculates the bbox of the first line in a wrapped text, fixing the way it's displayed/

fix: fix text wrap
