packages/docs/docs/advanced/custom-font.mdx
=> docs: add custom font

packages/core/src/player/Player.ts
=> fix(core): fix looping

packages/vite-plugin/src/main.ts
This commit makes it possible to run Motion Canvas in GitHub Codespaces.
Closes: #201
=> fix(vite-plugin): add missing headers to html

packages/2d/src/utils/CanvasUtils.ts
=> fix(2d): improve Rect radius

packages/2d/src/components/CodeBlock.ts
=> Stop code highlighting from jumping

packages/core/src/Project.ts, packages/core/src/scenes/GeneratorScene.ts, packages/core/src/scenes/Scene.ts, packages/core/src/scenes/Variables.ts, packages/core/src/scenes/index.ts, packages/docs/docs/advanced/project-variables.mdx, packages/player/src/main.ts
Closes #222 
Adds project variables :) Happy to add documentation in this PR or separately.
Can be tested by updating the example to include:
```
const circleFill = useScene().variables.get('circleFill');
view.add(<Circle ref={circle} width={320} height={320} fill={circleFill} />);
```
And either by adding variables to makeProject like:
```
export default makeProject({
scenes: [example],
background: '#141414',
variables: {circleFill: 'teal'},
});
```
Or by updating the player html (this shows variables being updated during the animation):
```
<body>
<script type="module" src="/src/main.ts"></script>
<button id="change-colour-variable">Change Colour</button>
<motion-canvas-player
src="/@id/__x00__virtual:template"
style="aspect-ratio: 16 / 9"
variables='{"circleFill":"red"}' …
```
=> Project variables

packages/core/src/tweening/timingFunctions.ts
Add all easing functions from easings.net and export sensible defaults for back, bounce and elastic easings.
Closes #220
=> feat(core): additional easing functions

packages/ui/src/components/playback/PlaybackControls.tsx
Fixed play-pause focus issue with spacebar when the element is already selected with mouse.
Added preventDefault funcion to the case.
Solves #273
=> Fix (UI) : Play-Pause with Spacebar , Fixes #273

FUNDING.yml
=> docs: add FUNDING.yml

packages/docs/docs/getting-started/tweening.mdx
https://proofed.com/writing-tips/spelling-tips-receive-or-recieve/
=> Fix a typo

packages/2d/src/components/Text.ts
This pr makes sure that the text displayed via the `Text` node is formatted 
according to the HTML rules. Duplicated whitespaces get removed, etc.
`textWrap={'pre'}` can still be used to preserve whitespaces.
Closes: #370
=> fix(2d): format whitespaces according to HTML

packages/2d/src/components/View2D.ts
Closes #367.
Worked locally for me, unsure if it could cause issues elsewhere but examples seem fine :D.
=> feat(2d): make `View2D` extend `Rect`

packages/core/src/tweening/index.ts, packages/core/src/tweening/spring.test.ts, packages/core/src/tweening/spring.ts
Resolves #334
I am very excited to contribute to the project again. I would really appreciate a code review. Please feel free and do not hesitate to point out best practices or wrong concepts.
I've added partly random example springs to choose from and an interface, but I really don't know if this really fits the overall code style of MC. 
Some notes to the tests: 
I noticed that the springs are very sensitive to the projects frame rate. I assume that the higher the frame rate, the steps are smaller and result in a more accurate simulation. Actually MC crashes at 10 fps and I do not have any clue why this happens – maybe a floating point issue.
Usage:
```ts
yield* spring(smoothSpring, 0, 100, .5, x => circle().position.x(x))
yield* spring({
mass: .3,
stiffness: 10,
damping: .1
}, 0, 100, …
```
=> feat(core): added spring interpolation

packages/core/src/transitions/fadeTransition.ts, packages/core/src/transitions/index.ts, packages/docs/docs/getting-started/transitions.mdx
=> Add simple fade transition

packages/2d/src/components/Rect.ts
Documents changes made in #281 
Added documentation to `smoothCorners` and `cornerSharpness`.
=> feat(2d, docs): added documentation for smoothCorners, cornerSharpness

packages/2d/src/components/Layout.ts, packages/2d/src/partials/types.ts
This PR adds `alignContent` and `alignSelf` properties to the Layout class.
=> feat: add missing flexbox properties

packages/core/src/Project.ts
=> fix(core): clear semi-transparent backgrounds

package-lock.json, packages/2d/package.json, packages/2d/src/components/CodeBlock.ts, packages/2d/src/components/index.ts, packages/docs/blog/2023-02-24-version-2.6.0.mdx
=> revert: feat: upgrade code-fns for new theme options and lazy loading

packages/2d/src/components/Layout.ts, packages/2d/src/components/Txt.ts, packages/2d/src/partials/types.ts
=> fix(2d): fix letterSpacing

packages/2d/src/scenes/Scene2D.ts, packages/core/src/scenes/GeneratorScene.ts
=> fix: support multiple async players

packages/2d/src/components/Layout.ts, packages/2d/src/components/Txt.ts
=> feat(2d): add textAlign property

packages/core/src/flow/scheduling.test.ts, packages/core/src/scenes/timeEvents/EditableTimeEvents.ts, packages/core/src/scenes/timeEvents/ReadOnlyTimeEvents.ts, packages/core/src/scenes/timeEvents/TimeEvents.ts, packages/core/src/threading/Thread.ts, packages/core/src/utils/useDuration.ts
Makes sure the fixed time is correctly inherited by new threads.
=> fix(core): fix relative time

packages/2d/src/components/Line.ts, packages/2d/src/curves/CurveProfile.ts, packages/2d/src/curves/getPolylineProfile.ts
=> fix(2d): fix cache bbox for lines

packages/2d/src/components/Node.ts, packages/2d/src/decorators/filtersSignal.ts, packages/2d/src/scenes/Scene2D.ts, packages/core/src/app/Player.ts, packages/core/src/app/Presenter.ts, packages/core/src/app/Renderer.ts, packages/core/src/scenes/GeneratorScene.ts, packages/core/src/scenes/Scene.ts
Cache is now stored using world space coordinates. This prevents quality loss when scaling up cached nodes.
Closes: #342
=> feat: world space cache

packages/2d/src/curves/getPolylineProfile.ts
=> fix(2d): fix line arc length

packages/docs/docs/components/code-block.mdx
=> docs: correct import for CodeBlock

packages/2d/src/components/Layout.ts, packages/2d/src/components/Node.ts, packages/2d/src/scenes/Scene2D.ts
Errors that occur during disposal are now correctly handled.
=> fix(2d): better error handling

package-lock.json, package.json, packages/core/package.json, packages/create/template-2d-js/package.json, packages/create/template-2d-ts/package.json, packages/e2e/package.json, packages/vite-plugin/package.json
This PR updated Vite version from v3 to v4 is mentioned here #197. 
I have run all the build commands and no error was found.
=> feat(core,create,vite-plugin): update vite from v3 to v4

packages/2d/src/jsx-dev-runtime.ts
=> fix(2d): add missing jsx dev runtime

packages/2d/src/jsx-dev-runtime.ts
=> fix(2d): add missing Fragment export

packages/2d/src/components/Node.ts
=> fix(2d): fix nested cache canvases

packages/2d/src/components/Layout.ts
=> fix(2d): clone size correctly

packages/2d/src/components/CodeBlock.ts
=> fix(2d): fix CodeBlock types

packages/2d/src/components/Video.ts
=> fix(2d): smoothly play videos when presenting

packages/2d/src/components/Layout.ts, packages/2d/src/components/Node.ts, packages/2d/src/decorators/compound.ts, packages/2d/src/decorators/signal.test.ts, packages/2d/src/decorators/signal.ts, packages/2d/src/utils/patchSignal.ts, packages/docs/docs/getting-started/layouts.mdx
=> feat(2d): add cardinal points

packages/docs/docs/getting-started/layouts.mdx
The example description doesn't seem to mention anything about circle, also the variable name suggests it's a rectangle
=> docs(fix): update example

packages/core/src/signals/DependencyContext.ts
=> fix(core): clear DependencyContext promises once resolved

packages/core/package.json, packages/core/src/types/Color.ts, packages/docs/docs/getting-started/tweening.mdx
=> fix: prevent Color tree shaking

packages/2d/src/components/Layout.ts
=> fix(2d): ignore children with disabled layout

packages/2d/src/components/Img.ts
=> fix(2d): correctly support external image urls

packages/docs/docs/getting-started/rendering/index.mdx, packages/ui/src/components/controls/Button.tsx, packages/ui/src/components/controls/Controls.module.scss, packages/ui/src/components/sidebar/VideoSettings.tsx, packages/ui/src/index.scss
The `RENDER` button now displays an animation to indicate that the rendering is in progress.
=> feat(2d): visual feedback about rendering process

packages/docs/docs/getting-started/flow.mdx
=> docs: add looping section to flow

CONTRIBUTING.md
=> docs: add AI section to CONTRIBUTING.md

packages/docs/src/components/Fiddle/folding.ts, packages/docs/src/components/Fiddle/index.tsx, packages/docs/src/components/Fiddle/styles.module.css
Import statements in fiddles are now folded.
=> feat(docs): import folding

packages/docs/docs/components/code-block.mdx
=> docs: add durations to code block selection yields

packages/ui/src/components/viewport/ColorPicker.tsx
=> fix(ui): prevent spawning multiple color pickers

.github/workflows/docs.yml, packages/core/src/types/Color.ts
=> fix(docs): fix last updated footer

packages/2d/src/curves/CircleSegment.ts
=> fix(2d): point arrow heads in correct direction

packages/ui/src/components/timeline/Timeline.tsx
Holding MMB over the timeline lets you drag it left and right.
Closes: #699
=> feat(ui): timeline dragging

packages/core/src/scenes/timeEvents/EditableTimeEvents.ts
=> fix(core): handle malicious event names

packages/core/src/types/Vector.ts
This PR adds static properties﻿ corresponding to the all currently available Origins.
Resolves #844.
=> feat(core): add static properties to Vector2 corresponding to Origins

packages/2d/src/lib/components/Layout.ts
=> fix(2d): account for offset in cardinal points

packages/2d/src/lib/scenes/makeScene2D.ts, packages/core/src/app/Project.ts, packages/core/src/app/bootstrap.ts, packages/core/src/meta/EnumMetaField.ts, packages/core/src/meta/ExporterMetaFile.ts, packages/core/src/plugin/DefaultPlugin.ts, packages/core/src/plugin/Plugin.ts, packages/core/src/scenes/Scene.ts, packages/docs/docs/advanced/plugins/editor.mdx, packages/docs/docs/advanced/plugins/index.mdx, packages/docs/docs/advanced/plugins/node.mdx, packages/docs/docs/advanced/plugins/runtime.mdx, packages/template/vite.config.ts, packages/ui/package.json, packages/ui/src/main.tsx, packages/ui/src/plugin/EditorPlugin.ts, packages/ui/src/plugin/makeEditorPlugin.ts, packages/ui/tsconfig.plugin.json, packages/vite-plugin/src/main.ts
Editor plugins now extend normal plugins
=> refactor: merge runtime and editor plugins

CHANGELOG.md, lerna.json, package-lock.json, packages/2d/CHANGELOG.md, packages/2d/package.json, packages/create/CHANGELOG.md, packages/create/package.json, packages/ui/CHANGELOG.md, packages/ui/package.json
This reverts commit 0a8ecbde5613a0d2328b9fcaf00ef51342f75ed6.
=> revert: ci(release): 3.12.4 [skip ci]

packages/2d/src/editor/NodeInspectorConfig.tsx, packages/2d/src/editor/PreviewOverlayConfig.tsx, packages/2d/src/editor/Provider.tsx, packages/2d/src/editor/SceneGraphTabConfig.tsx, packages/2d/src/editor/index.ts, packages/2d/src/editor/tree/DetachedRoot.tsx, packages/2d/src/editor/tree/NodeElement.tsx, packages/2d/src/editor/tree/ViewRoot.tsx, packages/ui/src/components/viewport/EditorPreview.tsx, packages/ui/src/components/viewport/Inspector.tsx, packages/ui/src/components/viewport/Viewport.module.scss, packages/ui/src/contexts/application.tsx, packages/ui/src/contexts/panels.tsx, packages/ui/src/plugin/EditorPlugin.ts
Displays the previously removed node inspector on the right
=> feat(ui): custom inspectors

packages/core/src/app/Player.ts, packages/core/src/app/ProjectMetadata.ts, packages/core/src/meta/NumberMetaField.ts, packages/ui/src/components/meta/NumberMetaFieldView.tsx
=> fix: limit fps to positive numbers

packages/2d/src/lib/components/Spline.ts, packages/2d/src/lib/curves/getBezierSplineProfile.ts
=> fix(2d): fix spline warning for reactive points

packages/examples/src/code.meta, packages/examples/src/code.ts, packages/examples/src/scenes/code.meta, packages/examples/src/scenes/code.tsx, packages/examples/vite.config.ts
My proposed solution for issue #1022
=> feat(docs): add Code node documentation

packages/2d/src/lib/code/CodeMetrics.ts
=> fix(2d): fix Code size calculation

packages/2d/src/lib/components/Layout.ts
=> fix(2d): fix layout gap prop type

packages/2d/src/lib/components/Node.ts
=> fix(2d): fix shader destination uv

packages/core/src/scenes/timeEvents/EditableTimeEvents.ts
=> fix(core): handle invalid time event values

packages/docs/docs/components/path.mdx
Improved the clarity of the docs for the `Path` component.
=> docs: improve `Path` documentation

packages/2d/src/lib/components/Polygon.ts
=> feat(2d): access vertex data of a Polygon

packages/2d/src/lib/components/Line.ts
=> fix(2d): fix line tweening

packages/2d/src/lib/components/Node.ts
=> fix(2d): prevent invalid cache sizes

packages/2d/src/lib/components/Code.ts
=> fix(2d): fix stack overflow for Code

packages/core/src/tweening/interpolationFunctions.ts
=> fix(2d): support tweening emojis

packages/ui/index.html, packages/ui/src/ProjectSelection.tsx, packages/vite-plugin/src/partials/editor.ts, packages/vite-plugin/src/partials/projects.ts, packages/vite-plugin/src/plugins.ts, packages/vite-plugin/src/utils.ts
fix issue of conflict with projects with same file name. Projects with same project file name in different folders, only runs the last project computed.
Fixes issue #1076
=> fix(vite-plugin, ui): project file path on selection

packages/2d/src/lib/components/Video.ts
=> fix(2d): add curve completion for videos

packages/2d/src/lib/components/Txt.ts
=> fix(2d): fix text height when tweening

packages/docs/docs/getting-started/tweening.mdx
Small drive-by PR. No worries if you'd rather fix it yourselves. :)
=> Fix small typo in the section on `spring` function

package-lock.json, packages/2d/package.json, packages/2d/src/lib/code/CodeRange.test.ts, packages/2d/src/lib/code/CodeRange.ts, packages/2d/src/lib/components/Code.ts
=> feat(2d): modifies  to match exact strings when passed a plain string

packages/core/src/app/ProjectMetadata.ts, packages/core/src/meta/NumberMetaField.ts, packages/ui/src/components/controls/NumberInput.tsx, packages/ui/src/components/meta/NumberMetaFieldView.tsx
Correctly configures the precision and step of the audio offset field to allow for fractional numbers.
=> fix: fix audio offset field
